### ISSUE TITLE
项目文件很多报错

### ISSUE THREAD

**Issue by McKenzieIT** [kadoufall/news-recommender#1]
你好请问项目是不是缺少了些东西，项目文件很多报错，很多方法找不到

**Comment by kadoufall** [comment]
哪里有错误可以截图看一下吗？

**Comment by wqyan** [comment]
很感谢您，错误我已经解决了。谢谢！


------------------ 原始邮件 ------------------
发件人: "kadoufall"<notifications@github.com>;
发送时间: 2019年4月29日(星期一) 中午1:41
收件人: "kadoufall/news-recommender"<news-recommender@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [kadoufall/news-recommender] 项目文件很多报错 (#1)




哪里有错误可以截图看一下吗？

**Comment by McKenzieIT** [comment]
> 哪里有错误可以截图看一下吗？

<img width="325" alt="image" src="https://user-images.githubusercontent.com/25838540/56878092-d26b8580-6a84-11e9-8a35-526b3b9d1def.png">
<img width="597" alt="image" src="https://user-images.githubusercontent.com/25838540/56878097-db5c5700-6a84-11e9-8411-ea1ae524d026.png">

**Comment by McKenzieIT** [comment]
> 很感谢您，错误我已经解决了。谢谢！
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "kadoufall"<notifications@github.com>; 发送时间: 2019年4月29日(星期一) 中午1:41 收件人: "kadoufall/news-recommender"<news-recommender@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: Re: [kadoufall/news-recommender] 项目文件很多报错 (#1) 哪里有错误可以截图看一下吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

解决了？

**Comment by wqyan** [comment]
是的。已经解决了。




------------------ 原始邮件 ------------------
发件人: "McKenzie"<notifications@github.com>;
发送时间: 2019年4月29日(星期一) 中午1:44
收件人: "kadoufall/news-recommender"<news-recommender@noreply.github.com>;
抄送: "严文强"<643320250@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [kadoufall/news-recommender] 项目文件很多报错 (#1)



 
很感谢您，错误我已经解决了。谢谢！
 …
 ------------------ 原始邮件 ------------------ 发件人: "kadoufall"notifications@github.com; 发送时间: 2019年4月29日(星期一) 中午1:41 收件人: "kadoufall/news-recommender"news-recommender@noreply.github.com; 抄送: "Subscribed"subscribed@noreply.github.com; 主题: Re: [kadoufall/news-recommender] 项目文件很多报错 (#1) 哪里有错误可以截图看一下吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
解决了？

**Comment by McKenzieIT** [comment]
> 是的。已经解决了。
> […](#)

那可以更新代码看看？

**Comment by wqyan** [comment]
嗯。。好的




------------------ 原始邮件 ------------------
发件人: "McKenzie"<notifications@github.com>;
发送时间: 2019年4月29日(星期一) 中午1:46
收件人: "kadoufall/news-recommender"<news-recommender@noreply.github.com>;
抄送: "严文强"<643320250@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [kadoufall/news-recommender] 项目文件很多报错 (#1)



 
是的。已经解决了。
 …
  
那可以更新代码看看？

**Comment by McKenzieIT** [comment]
> 嗯。。好的
> […](#)

你好，代码是更新了吗？我还是原来的问题

**Comment by kadoufall** [comment]
看截图的问题，可能是因为：
- JDK版本低于1.8
- 没有装 [Lombok](https://projectlombok.org/)

**Comment by McKenzieIT** [comment]
> 看截图的问题，可能是因为：
> 
> * JDK版本低于1.8
> * 没有装 [Lombok](https://projectlombok.org/)

<img width="380" alt="image" src="https://user-images.githubusercontent.com/25838540/56887870-4453c700-6aa5-11e9-9e55-360d24e386a1.png">
<img width="217" alt="image" src="https://user-images.githubusercontent.com/25838540/56887887-4c136b80-6aa5-11e9-8520-9deadabbdabe.png">
应该不是这两个问题
